<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <ProjectReference Include="../../src/Mambo.Core/Mambo.Core.csproj" />
    <ProjectReference Include="../../src/Mambo.Player/Mambo.Player.csproj" />
    <None Include="../../third_party/libmpv/bin/libmpv-2.dll" Link="mpv/libmpv-2.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('../../third_party/libmpv/bin/libmpv-2.dll')" />
  </ItemGroup>
</Project>
