param([switch]$Verify)
$ErrorActionPreference = 'Stop'
$shaderRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../third_party/shaders'))
$lock = Get-Content -LiteralPath (Join-Path $shaderRoot 'shaders.lock.json') -Raw | ConvertFrom-Json
foreach ($entry in $lock.upstream) {
    $actual = (Get-FileHash -LiteralPath (Join-Path $shaderRoot $entry.path) -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actual -ne $entry.sha256) { throw "上游着色器校验失败：$($entry.path)" }
}
function Read-Source([string]$relative) {
    return [IO.File]::ReadAllText((Join-Path $shaderRoot $relative)).Replace("`r`n", "`n").TrimEnd() + "`n"
}
$common = Read-Source 'adapters/common.glsl'
$kernel = Read-Source 'adapters/cas.glsl'
function Read-Adapter([string]$name) {
    return (Read-Source "adapters/$name.glsl").Replace('{{COMMON}}', $common).Replace('{{CAS}}', $kernel)
}
function Read-Anime([string]$name) {
    $source = Read-Source "upstream/anime4k/$name.glsl"
    return [regex]::Replace($source, '(?m)^//!DESC (.+)$', '//!DESC Mambo Anime $1')
}
function Add-Resampling([string]$source) {
    # Mirror every size-changing MAIN pass on both private baselines before MAIN changes.
    # This preserves the identical sampling history even with two upscalers/downscalers.
    $blocks = [regex]::Split($source, '(?m)(?=^//!DESC )')
    $result = ''
    foreach ($block in $blocks) {
        if ($block -notmatch '(?m)^//!WIDTH (.+)$') { $result += $block; continue }
        $width = $Matches[1]
        if ($block -notmatch '(?m)^//!HEIGHT (.+)$') { throw 'Missing height' }
        $height = $Matches[1]
        if ($block -notmatch '(?m)^//!WHEN (.+)$') { $result += $block; continue }
        $when = $Matches[1]
        $resizesMain = $block -match '(?m)^//!SAVE MAIN$' -or $block -match 'AutoDownscalePre'
        if ($resizesMain) {
            foreach ($buffer in @('MAMBO_A4K_BASE', 'MAMBO_A4K_ORIGINAL')) {
                $components = if ($buffer -eq 'MAMBO_A4K_BASE') { 2 } else { 4 }
                $result += @"
//!DESC Mambo Anime resample $buffer
//!HOOK MAIN
//!BIND $buffer
//!SAVE $buffer
//!WIDTH $width
//!HEIGHT $height
//!WHEN $when
//!COMPONENTS $components
vec4 hook() { return ${buffer}_tex(${buffer}_pos); }

"@
            }
        }
        $result += $block
    }
    return $result
}
$cas = Read-Source 'upstream/cas/ffx_cas.h'
$licenseStart = $cas.IndexOf('// LICENSE')
$licenseEnd = $cas.IndexOf('// ABOUT', $licenseStart)
$casLicense = $cas.Substring($licenseStart, $licenseEnd - $licenseStart)
$clear = '// Generated by scripts/build-video-shaders.ps1; edit adapters, not runtime files.' + "`n" + $casLicense + (Read-Adapter 'clear')
$clamp = Read-Anime 'Anime4K_Clamp_Highlights'
$clampHeader = "//!HOOK PREKERNEL`n//!BIND HOOKED`n//!BIND STATSMAX"
if (!$clamp.Contains($clampHeader)) { throw 'Anime4K Clamp 上游结构已变化，无法注入 HDR 保护。' }
$clamp = $clamp.Replace($clampHeader, "$clampHeader`n$common")
$clamp = $clamp.Replace('float current_luma =', 'if (mamboIsHdr()) return HOOKED_tex(HOOKED_pos);' + "`n    float current_luma =")
$anime = '// Generated by scripts/build-video-shaders.ps1; edit adapters, not runtime files.' + "`n" + (Read-Adapter 'anime-enter') + $clamp
$anime += Read-Anime 'Anime4K_Restore_CNN_Soft_M'
foreach ($name in @('Anime4K_Upscale_CNN_x2_M', 'Anime4K_AutoDownscalePre_x2', 'Anime4K_AutoDownscalePre_x4', 'Anime4K_Upscale_CNN_x2_S')) {
    $anime += Add-Resampling (Read-Anime $name)
}
$anime += Read-Adapter 'anime-exit'
$outputs = [ordered]@{'Mambo_Clear.glsl' = $clear; 'Mambo_Anime.glsl' = $anime}
$manifest = @()
foreach ($entry in $outputs.GetEnumerator()) {
    foreach ($block in [regex]::Split($entry.Value, '(?m)(?=^//!DESC )')) {
        $helpers = @([regex]::Matches($block, '\b(mambo[A-Za-z0-9_]+)\s*\(') | ForEach-Object { $_.Groups[1].Value } | Select-Object -Unique)
        foreach ($helper in $helpers) {
            $definitions = [regex]::Matches($block, "\b(?:bool|float|vec[234])\s+$helper\s*\(").Count
            if ($definitions -ne 1) { throw "着色器 pass 的 helper 定义数量错误：$($entry.Key) / $helper" }
        }
    }
    $relative = 'runtime/' + $entry.Key
    $path = Join-Path $shaderRoot $relative
    # Windows checkout 将 PowerShell 的 here-string 变为 CRLF；运行时锁定资源统一使用 LF。
    $bytes = [Text.Encoding]::UTF8.GetBytes($entry.Value.Replace("`r`n", "`n"))
    if ($Verify) {
        if (!(Test-Path -LiteralPath $path) -or ![Linq.Enumerable]::SequenceEqual[byte]([IO.File]::ReadAllBytes($path), $bytes)) {
            throw "运行时着色器不是当前输入的生成结果：$relative"
        }
    } else { [IO.File]::WriteAllBytes($path, $bytes) }
    $manifest += [ordered]@{path=$relative;sha256=[Convert]::ToHexStringLower([Security.Cryptography.SHA256]::HashData($bytes));bytes=$bytes.Length}
}
$manifestJson = ([ordered]@{schemaVersion=1;generator='scripts/build-video-shaders.ps1';files=$manifest} | ConvertTo-Json -Depth 4).Replace("`r`n", "`n") + "`n"
$manifestPath = Join-Path $shaderRoot 'runtime/manifest.json'
if ($Verify) {
    if (!(Test-Path -LiteralPath $manifestPath) -or [IO.File]::ReadAllText($manifestPath) -cne $manifestJson) { throw '运行时着色器清单不匹配。' }
} else { [IO.File]::WriteAllText($manifestPath, $manifestJson, [Text.UTF8Encoding]::new($false)) }
Write-Output '画质着色器源码、生成结果与 SHA-256 校验通过。'
